# markdown
markdown: kramdown
kramdown:
  extensions: ["superscript","tables","with_toc_data","strikethrough","smart"]
highlighter: rouge

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# Site metadata
name: "U.S. Emerging Citizen Technology Atlas"
description: "All of the federal emerging citizen technology."
baseurl: ""

# Google Analytics
google_analytics: UA—110413123-1

# Uncomment the following line for localhost development at http://127.0.0.1:4000/software/
# baseurl: /software

# GitHub information
org_name: gsa
repo_name: emerging-technology-atlas
branch: master

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: "Home"
  url: /
- text: "Latest Updates"
  url: /updates/
- text: "How to Contribute"
  url: /howto/
- text: "About Emerging Citizen Technology Office"
  url: /emergingcitizentech/
  sub_nav:
  - text: <span>Participating Agencies in ECTO</span>
    url: /participatingagencies/
- text: "Meeting Notes"
  url: /Meeting-Notes/
- text: "Events Calendar"
  url: /calendar/
- text: "Artificial Intelligence"
  url: /artificial-intelligence/
- text: "Blockchain"
  url: /Blockchain/

main_navigation:
- text: "How to Contribute"
  url: /howto/
