# markdown
markdown: kramdown
kramdown:
  extensions: ["superscript","tables","with_toc_data","strikethrough","smart"]
highlighter: rouge

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# Site metadata
name: "Emerging Technology Atlas"
description: "Some information about GSA in general."
baseurl: /emerging-technology-atlas

# Uncomment the following line for localhost development at http://127.0.0.1:4000/software/
# baseurl: /software

# GitHub information
org_name: gsa
repo_name: emerging-technology-atlas
branch: master

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: "Home"
  url: /
- text: "How to Contribute"
  url: /howto/
- text: "About Emerging Citizen Technology Program"
  url: /emergingcitizentech/
  
- text: "Artificial Intelligence for Citizen Services"
  url: /artificial-intelligence/

  sub_navigation:
  - text: "Federal Use Cases</span>"
    url: /artificial-intelligence-federal/
  - text: "Programs</span>"
    url: /artificial-intelligence-programs/
  - text: "Resources</span>"
    url: /artificial-intelligence-resources/
  - text: "Events</span>"
    url: /artificial-intelligence-events/
    
- text: "Blockchain"
  url: /Blockchain/
  
  sub_navigation:
  - text: "Federal Use Cases</span>"
    url: /blockchain-federal/
  - text: "Programs</span>"
    url: /blockchain-programs/
  - text: "Resources</span>"
    url: /blockchain-resources/
  - text: "Events</span>"
    url: /blockchain-events/

- text: "Virtual and Augmented Reality (Coming Soon)"
  url: /virtual-reality/

- text: "Social Technology (Coming Soon)"
  url: /social-technology/
